### ISSUE TITLE
Creation of save9999.dat

### ISSUE THREAD

**Issue by Henry1887** [Gezine/ArtemisLuaLoader#8]
Hello, im trying to replicate this on pc and wanted to ask how exactly you managed to create a custom save9999.dat file that loads the inject.iet? I tried using the one you provided but i guess it isnt compatible with my game on pc. I tried to replicate your save9999.dat file by editing a save file created by my game and adding the injection iet file just like in your file but i cant get it to work as i have no idea how exactly the artemis engine parses the data inside the save file. Could you help me out here?

**Comment by Henry1887** [comment]
nvm i managed to adjust the one you provided and now it works.

**Comment by dtristany** [comment]
@Gezine 
I'm also trying to understand the structure of the .dat save files used in Artemis games. I've tried using binwalk and a Python script to decompress zlib sections (starting at offset 8), but haven't had much success unpacking or identifying the file table layout.

Would really appreciate any pointers to documentation, past discussions, or even just outline of your workflow for analyzing and modifying.
